using System;

namespace InstantAIGate.Infrastructure.Inference.Native
{
    /// <summary>
    /// Abstraction layer over the native libmtmd multimodal API.
    /// Works in tandem with INativeLlamaApi to process images and audio.
    /// </summary>
    public interface INativeMtmdApi
    {

        /// <summary>
        /// Retrieves the expected image marker string from the specified multimodal context.
        /// Returns a fallback "<image>" marker if the provided context pointer is zero, the native marker pointer is unallocated, or if string marshaling fails.
        /// </summary>
        /// <param name="mtmdContext">A pointer to the initialized native multimodal context.</param>
        /// <returns>The string representation of the expected image marker.</returns>
        string GetExpectedImageMarker(IntPtr mtmdContext);

        /// <summary>
        /// Retrieves the capabilities of a multimodal projector model.
        /// </summary>
        /// <param name="projectorPath">Path to the mmproj file.</param>
        /// <returns>Capabilities of the multimodal model.</returns>
        MultimodalCapabilities GetCapabilities(string projectorPath);

        /// <summary>
        /// Initializes a multimodal context linked to an existing text model.
        /// </summary>
        /// <param name="projectorPath">Path to the mmproj file.</param>
        /// <param name="textModelPtr">Pointer to the initialized text model.</param>
        /// <param name="useGpu">Determines whether to utilize GPU acceleration.</param>
        /// <returns>Pointer to the initialized multimodal context.</returns>
        IntPtr InitializeContext(string projectorPath, IntPtr textModelPtr, bool useGpu);

        /// <summary>
        /// Frees the multimodal context and its resources.
        /// </summary>
        /// <param name="mtmdContext">Pointer to the multimodal context.</param>
        void FreeContext(IntPtr mtmdContext);

        /// <summary>
        /// Allocates a native bitmap structure for an image.
        /// </summary>
        /// <param name="width">Image width in pixels.</param>
        /// <param name="height">Image height in pixels.</param>
        /// <param name="rgbData">Pinned pointer to raw RGB byte array.</param>
        /// <returns>Pointer to the created native bitmap.</returns>
        IntPtr CreateBitmap(uint width, uint height, IntPtr rgbData);

        /// <summary>
        /// Frees a native bitmap structure.
        /// </summary>
        /// <param name="bitmap">Pointer to the native bitmap.</param>
        void FreeBitmap(IntPtr bitmap);

        /// <summary>
        /// Allocates a native chunk list container.
        /// </summary>
        /// <returns>Pointer to the chunk collection.</returns>
        IntPtr CreateInputChunks();

        /// <summary>
        /// Frees the native chunk list container.
        /// </summary>
        /// <param name="chunks">Pointer to the chunk collection.</param>
        void FreeInputChunks(IntPtr chunks);

        /// <summary>
        /// Tokenizes a prompt and merges it with the provided bitmaps into chunks.
        /// </summary>
        /// <param name="mtmdContext">Pointer to the multimodal context.</param>
        /// <param name="outputChunks">Pointer to the output chunk collection.</param>
        /// <param name="text">Input text containing media markers.</param>
        /// <param name="bitmaps">Array of pointers to native bitmaps.</param>
        /// <returns>Status code of the tokenization process.</returns>
        int Tokenize(IntPtr mtmdContext, IntPtr outputChunks, string text, IntPtr[] bitmaps);

        /// <summary>
        /// Encodes a specific media chunk through the projector network to generate embeddings.
        /// </summary>
        /// <param name="mtmdContext">Pointer to the multimodal context.</param>
        /// <param name="chunk">Pointer to the chunk to encode.</param>
        /// <returns>Status code of the encoding process.</returns>
        int EncodeChunk(IntPtr mtmdContext, IntPtr chunk);

        /// <summary>
        /// Retrieves the flat array of float embeddings generated by the last encode pass.
        /// </summary>
        /// <param name="mtmdContext">Pointer to the multimodal context.</param>
        /// <param name="nTokens">Number of tokens processed.</param>
        /// <param name="nEmbdDim">Embedding dimension size.</param>
        /// <returns>A managed array containing the embeddings.</returns>
        float[] GetOutputEmbeddings(IntPtr mtmdContext, int nTokens, int nEmbdDim);

        /// <summary>
        /// Gets the total number of chunks in the container.
        /// </summary>
        /// <param name="chunks">Pointer to the chunk collection.</param>
        /// <returns>Number of chunks.</returns>
        int GetChunksCount(IntPtr chunks);

        /// <summary>
        /// Retrieves a pointer to a specific chunk by its index.
        /// </summary>
        /// <param name="chunks">Pointer to the chunk collection.</param>
        /// <param name="index">Zero-based index of the chunk.</param>
        /// <returns>Pointer to the specified chunk.</returns>
        IntPtr GetChunk(IntPtr chunks, int index);

        /// <summary>
        /// Identifies the type of the specified chunk.
        /// </summary>
        /// <param name="chunk">Pointer to the chunk.</param>
        /// <returns>The domain-mapped chunk type.</returns>
        InputChunkType GetChunkType(IntPtr chunk);

        /// <summary>
        /// Gets the number of tokens contained within the specified chunk.
        /// </summary>
        /// <param name="chunk">Pointer to the chunk.</param>
        /// <returns>Token count.</returns>
        int GetChunkTokenCount(IntPtr chunk);

        /// <summary>
        /// Extracts the text tokens from a text chunk.
        /// </summary>
        /// <param name="chunk">Pointer to the chunk.</param>
        /// <returns>Array of text tokens.</returns>
        int[] GetChunkTokens(IntPtr chunk);

        /// <summary>
        /// Initializes a multimodal batch for encoding.
        /// </summary>
        /// <param name="mtmdContext">Pointer to the multimodal context.</param>
        /// <returns>Pointer to the initialized batch.</returns>
        IntPtr BatchInit(IntPtr mtmdContext);

        /// <summary>
        /// Frees the allocated multimodal batch.
        /// </summary>
        /// <param name="batch">Pointer to the batch.</param>
        void BatchFree(IntPtr batch);

        /// <summary>
        /// Adds a chunk to the multimodal batch.
        /// </summary>
        /// <param name="batch">Pointer to the batch.</param>
        /// <param name="chunk">Pointer to the chunk.</param>
        void BatchAddChunk(IntPtr batch, IntPtr chunk);

        /// <summary>
        /// Encodes the multimodal batch.
        /// </summary>
        /// <param name="batch">Pointer to the batch.</param>
        /// <returns>Status code of the encoding process.</returns>
        int BatchEncode(IntPtr batch);
    }
}