using System;

namespace InstantAIGate.Infrastructure.Inference.Native
{
    /// <summary>
    /// Abstraction layer over the new libmtmd multimodal API.
    /// Works in tandem with INativeLlamaApi to process images and audio.
    /// </summary>
    public interface INativeMtmdApi
    {
        /// <summary>
        /// Retrieves the capabilities of a multimodal projector model.
        /// </summary>
        NativeMethods.mtmd_caps GetCapabilities(string projectorPath);

        /// <summary>
        /// Initializes a multimodal context linked to an existing text model.
        /// </summary>
        /// <param name="projectorPath">Path to the mmproj file.</param>
        /// <param name="textModelPtr">Pointer to the initialized llama_model.</param>
        /// <param name="useGpu">Whether to offload projector calculations to GPU.</param>
        /// <returns>Pointer to the mtmd_context.</returns>
        IntPtr InitializeContext(string projectorPath, IntPtr textModelPtr, bool useGpu);

        /// <summary>
        /// Frees the multimodal context and its resources.
        /// </summary>
        void FreeContext(IntPtr mtmdContext);

        /// <summary>
        /// Allocates a native bitmap structure for an image.
        /// </summary>
        /// <param name="width">Image width in pixels.</param>
        /// <param name="height">Image height in pixels.</param>
        /// <param name="rgbData">Pinned pointer to raw RGB byte array (width * height * 3).</param>
        /// <returns>Pointer to mtmd_bitmap.</returns>
        IntPtr CreateBitmap(uint width, uint height, IntPtr rgbData);

        /// <summary>
        /// Frees a native bitmap structure.
        /// </summary>
        void FreeBitmap(IntPtr bitmap);

        /// <summary>
        /// Allocates a native chunk list container.
        /// </summary>
        IntPtr CreateInputChunks();

        /// <summary>
        /// Frees the native chunk list container.
        /// </summary>
        void FreeInputChunks(IntPtr chunks);

        /// <summary>
        /// Tokenizes a prompt and merges it with the provided bitmaps into chunks.
        /// </summary>
        int Tokenize(IntPtr mtmdContext, IntPtr outputChunks, string text, IntPtr[] bitmaps);

        /// <summary>
        /// Encodes a specific media chunk through the projector network to generate embeddings.
        /// </summary>
        int EncodeChunk(IntPtr mtmdContext, IntPtr chunk);

        /// <summary>
        /// Retrieves the flat array of float embeddings generated by the last encode pass.
        /// </summary>
        /// <param name="mtmdContext">The multimodal context.</param>
        /// <param name="numEmbeddings">Out parameter returning the total number of floats.</param>
        /// <returns>A managed array containing the embeddings.</returns>
        float[] GetOutputEmbeddings(IntPtr mtmdContext, int nTokens, int nEmbdDim);
    }
}