#pragma once

#include <cstdint>

#if defined(_MSC_VER)
#define BRIDGE_API __declspec(dllexport)
#elif defined(__GNUC__)
#define BRIDGE_API __attribute__((visibility("default")))
#else
#define BRIDGE_API
#endif

extern "C" {

    /// <summary>
    /// Opaque handle representing the internal inference executor state.
    /// </summary>
    typedef struct ExecutorHandle ExecutorHandle;

    /// <summary>
    /// Represents the input data for a single inference generation cycle.
    /// </summary>
    struct InferenceRequest {
        /// <summary>
        /// Unique identifier for the request, used for routing responses.
        /// </summary>
        const char* requestId;

        /// <summary>
        /// Array of input tokens to be processed by the engine.
        /// </summary>
        const int32_t* tokens;

        /// <summary>
        /// The number of tokens in the tokens array.
        /// </summary>
        int32_t tokenCount;
    };

    /// <summary>
    /// Represents the output data generated by the inference engine.
    /// </summary>
    struct InferenceResponse {
        /// <summary>
        /// Unique identifier matching the original InferenceRequest.
        /// </summary>
        const char* requestId;

        /// <summary>
        /// Array of dynamically allocated tokens generated by the model.
        /// </summary>
        int32_t* generatedTokens;

        /// <summary>
        /// The number of tokens in the generatedTokens array.
        /// </summary>
        int32_t generatedTokenCount;

        /// <summary>
        /// Indicates if the engine has finished generating tokens for this request.
        /// </summary>
        bool isCompleted;
    };

    /// <summary>
    /// Initializes a new instance of the inference executor.
    /// Sets up internal thread-safe queues and synchronization primitives.
    /// </summary>
    /// <returns>A pointer to the initialized ExecutorHandle.</returns>
    BRIDGE_API ExecutorHandle* Bridge_InitializeExecutor();

    /// <summary>
    /// Safely enqueues a new inference request into the background processing queue.
    /// Wakes up the consumer thread upon successful insertion.
    /// </summary>
    /// <param name="handle">Pointer to the active executor state.</param>
    /// <param name="request">Pointer to the request payload.</param>
    /// <returns>true if the task was successfully enqueued; otherwise, false.</returns>
    BRIDGE_API bool Bridge_EnqueueTask(ExecutorHandle* handle, const InferenceRequest* request);

    /// <summary>
    /// Blocks the current thread until the engine produces a response.
    /// Uses condition variables to consume zero CPU cycles while waiting.
    /// </summary>
    /// <param name="handle">Pointer to the active executor state.</param>
    /// <returns>Pointer to a dynamically allocated InferenceResponse, or nullptr if the executor is shut down.</returns>
    BRIDGE_API InferenceResponse* Bridge_AwaitResponses(ExecutorHandle* handle);

    /// <summary>
    /// Performs a graceful shutdown of the executor.
    /// Wakes sleeping threads, clears pending tasks, and deallocates the handle memory.
    /// </summary>
    /// <param name="handle">Pointer to the executor state to be destroyed.</param>
    BRIDGE_API void Bridge_FreeMemory(ExecutorHandle* handle);

    /// <summary>
    /// Deallocates the memory for a specific inference response object and its internal arrays.
    /// Must be called by the client after reading the response to prevent memory leaks.
    /// </summary>
    /// <param name="response">Pointer to the response structure to free.</param>
    BRIDGE_API void Bridge_FreeResponse(InferenceResponse* response);
}