using InstantAIGate.Application.Dtos.Requests;
using InstantAIGate.Application.Interfaces.Inference;
using InstantAIGate.Application.Interfaces.Storage;
using InstantAIGate.Infrastructure.Inference.Native;
using InstantAIGate.Infrastructure.Templates;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace InstantAIGate.Infrastructure.Inference.Adapters
{
    /// <summary>
    /// Chat adapter that uses LLaMA models for text generation.
    /// Fully isolated from native P/Invoke calls through INativeLlamaApi.
    /// Supports both streaming and non-streaming inference with configurable sampling parameters.
    /// </summary>
    public class ChatAdapter : IChatAdapter
    {
        private readonly ModelManager _modelManager;
        private readonly IModelPathProvider _pathProvider;
        private readonly ILogger<ChatAdapter> _logger;
        private readonly NativeLlamaApi _nativeApi;

        /// <summary>
        /// Initializes a new instance of the ChatAdapter with required dependencies.
        /// </summary>
        public ChatAdapter(
            ModelManager modelManager,
            IModelPathProvider pathProvider,
            NativeLlamaApi nativeApi,
            ILogger<ChatAdapter> logger)
        {
            _modelManager = modelManager;
            _pathProvider = pathProvider;
            _nativeApi = nativeApi;
            _logger = logger;
        }

        /// <summary>
        /// Generates a complete response synchronously by consuming the streaming output.
        /// Collects all tokens from StreamAsync and returns the final concatenated text.
        /// </summary>
        public async Task<string> GenerateAsync(ChatRequest request, CancellationToken ct = default)
        {
            var sb = new StringBuilder();
            await foreach (var token in StreamAsync(request, ct))
            {
                sb.Append(token);
            }
            return sb.ToString();
        }

        /// <summary>
        /// Streams generated tokens asynchronously using Server-Sent Events pattern.
        /// Yields each decoded token as it is generated by the model.
        /// Supports configurable sampling parameters and smart context trimming (Sliding Window).
        /// </summary>
        public async IAsyncEnumerable<string> StreamAsync(ChatRequest request, [EnumeratorCancellation] CancellationToken ct = default)
        {
            var modelSettings = _modelManager.GetActiveSettings();
            if (modelSettings == null)
            {
                throw new InvalidOperationException("No active model is currently loaded in the system.");
            }

            string activeRepoId = modelSettings.RepoId;

            if (!string.Equals(request.Model, activeRepoId, StringComparison.OrdinalIgnoreCase))
            {
                _logger.LogDebug("Client requested '{RequestedModel}', dynamically routing to active model '{ActiveModel}'.", request.Model, activeRepoId);
            }

            string resolvedPath = await _pathProvider.GetFullModelPathAsync(activeRepoId);
            var profile = ModelProfileResolver.Resolve(resolvedPath);

            using var model = await _modelManager.AcquireModelAsync(activeRepoId, ct);
            using var context = await _modelManager.AcquireContextAsync(activeRepoId, ct);

            int nBatchLimit = (int)modelSettings.BatchSize;
            if (nBatchLimit <= 0)
            {
                nBatchLimit = 512;
                _logger.LogWarning("Invalid BatchSize in settings for '{Model}'. Falling back to 512.", activeRepoId);
            }

            int contextLimit = (int)modelSettings.ContextSize;
            int maxTokens = request.MaxTokens > 0 ? request.MaxTokens : 512;

            int availableTokensForPrompt = contextLimit - maxTokens;

            if (availableTokensForPrompt <= 0)
            {
                throw new InvalidOperationException($"Invalid context configuration. Context limit ({contextLimit}) must be greater than max generation tokens ({maxTokens}).");
            }

            IntPtr vocab = _nativeApi.ModelGetVocab(model.Handle);
            IntPtr ctxHandle = context.TextContext.Handle;

            var messages = request.Messages.ToList();

            string prompt = profile.Template.BuildPrompt(messages);
            byte[] promptBytes = Encoding.UTF8.GetBytes(prompt);

            int[] tokens = new int[contextLimit + maxTokens + 128];

            int nTokens = _nativeApi.Tokenize(
                vocab,
                prompt,
                promptBytes.Length,
                tokens,
                tokens.Length,
                false,
                true
            );

            if (nTokens < 0)
            {
                tokens = new int[-nTokens];
                nTokens = _nativeApi.Tokenize(vocab, prompt, promptBytes.Length, tokens, tokens.Length, false, true);
            }

            while (nTokens > availableTokensForPrompt)
            {
                int oldestMessageIndex = -1;

                for (int i = 0; i < messages.Count - 1; i++)
                {
                    if (messages[i].Role != "system")
                    {
                        oldestMessageIndex = i;
                        break;
                    }
                }

                if (oldestMessageIndex != -1)
                {
                    _logger.LogDebug("Context overflow: {Tokens}/{Limit}. Trimming historical message pair starting at index {Index}.", nTokens, availableTokensForPrompt, oldestMessageIndex);

                    messages.RemoveAt(oldestMessageIndex);

                    if (oldestMessageIndex < messages.Count && messages[oldestMessageIndex].Role == "assistant")
                    {
                        messages.RemoveAt(oldestMessageIndex);
                    }
                }
                else
                {
                    int lastMessageIndex = messages.FindLastIndex(m => m.Role != "system");

                    if (lastMessageIndex == -1)
                    {
                        break;
                    }

                    var lastMessage = messages[lastMessageIndex];

                    if (string.IsNullOrWhiteSpace(lastMessage.Content))
                    {
                        break;
                    }

                    int excessTokens = nTokens - availableTokensForPrompt;

       
                    byte[] contentBytes = Encoding.UTF8.GetBytes(lastMessage.Content);
                    int[] contentTokens = new int[contentBytes.Length + 128];
                    int messageTokenCount = _nativeApi.Tokenize(vocab, lastMessage.Content, contentBytes.Length, contentTokens, contentTokens.Length, false, true);

                    if (messageTokenCount > 0 && messageTokenCount > excessTokens)
                    {
                        int tokensToKeep = messageTokenCount - excessTokens - 10; 
                        if (tokensToKeep > 0)
                        {
                            var safeAccumulator = new StringBuilder();
                            var truncationDecoder = Encoding.UTF8.GetDecoder();
                            byte[] pieceBuffer = new byte[256];
                            char[] pieceChars = new char[512];

                            for (int i = messageTokenCount - tokensToKeep; i < messageTokenCount; i++)
                            {
                                int pieceSize = _nativeApi.TokenToPiece(vocab, contentTokens[i], pieceBuffer, pieceBuffer.Length, 0, false);
                                if (pieceSize > 0)
                                {
                                    int charsDecoded = truncationDecoder.GetChars(pieceBuffer, 0, pieceSize, pieceChars, 0, false);
                                    safeAccumulator.Append(new string(pieceChars, 0, charsDecoded));
                                }
                            }

                            truncationDecoder.GetChars(pieceBuffer, 0, 0, pieceChars, 0, true); // flush
                            messages[lastMessageIndex] = lastMessage with { Content = "..." + safeAccumulator.ToString() };
                        }
                        else
                        {
                            messages.RemoveAt(lastMessageIndex);
                        }
                    }
                    else
                    {
                        messages.RemoveAt(lastMessageIndex);
                    }

                    _logger.LogWarning("Context overflow: {Tokens}/{Limit}. Truncating the beginning of the last message.", nTokens, availableTokensForPrompt);
                }

                prompt = profile.Template.BuildPrompt(messages);
                promptBytes = Encoding.UTF8.GetBytes(prompt);

                nTokens = _nativeApi.Tokenize(vocab, prompt, promptBytes.Length, tokens, tokens.Length, false, true);

                if (nTokens < 0)
                {
                    tokens = new int[-nTokens];
                    nTokens = _nativeApi.Tokenize(vocab, prompt, promptBytes.Length, tokens, tokens.Length, false, true);
                }
            }

            if (nTokens > availableTokensForPrompt)
            {
                throw new InvalidOperationException($"Fatal error during context truncation. Tokens ({nTokens}) still exceed available window ({availableTokensForPrompt}).");
            }

            if (nTokens <= 0)
                throw new InvalidOperationException("Tokenization failed after context trimming.");

            var chainParams = _nativeApi.SamplerChainDefaultParams();
            IntPtr sampler = _nativeApi.SamplerChainInit(chainParams);

            _nativeApi.SamplerChainAdd(sampler, _nativeApi.SamplerInitTopK(request.TopK));
            _nativeApi.SamplerChainAdd(sampler, _nativeApi.SamplerInitTopP(request.TopP, (nuint)1));

            float temperature = request.Temperature > 0 ? request.Temperature : 0.7f;
            _nativeApi.SamplerChainAdd(sampler, _nativeApi.SamplerInitTemp(temperature));

            uint seed = request.Seed.HasValue ? (uint)request.Seed.Value : (uint)Random.Shared.Next();
            _nativeApi.SamplerChainAdd(sampler, _nativeApi.SamplerInitDist(seed));

            IntPtr repetitionSampler = _nativeApi.SamplerInitRepetition(
                1.1f,
                request.FrequencyPenalty,
                request.PresencePenalty
            );

            if (repetitionSampler != IntPtr.Zero)
            {
                _nativeApi.SamplerChainAdd(sampler, repetitionSampler);
            }
            else
            {
                _logger.LogWarning("Repetition sampler creation failed. Penalties will not be applied.");
            }


            for (int i = 0; i < nTokens; i++)
            {
                _nativeApi.SamplerAccept(sampler, tokens[i]);
            }

            int eos = _nativeApi.VocabEos(vocab);
            int currentPos = 0;
            int generated = 0;

            int maxBatchSize = nBatchLimit;

            int[] batchTokens = new int[maxBatchSize];
            int[] batchPos = new int[maxBatchSize];
            int[] batchNSeq = new int[maxBatchSize];
            sbyte[] batchLogits = new sbyte[maxBatchSize];

            int seqIdValue = 0;
            GCHandle hSeqIdValue = GCHandle.Alloc(seqIdValue, GCHandleType.Pinned);
            IntPtr ptrSeqIdValue = hSeqIdValue.AddrOfPinnedObject();

            IntPtr[] seqIdPointers = new IntPtr[maxBatchSize];
            for (int i = 0; i < maxBatchSize; i++)
            {
                seqIdPointers[i] = ptrSeqIdValue;
            }

            GCHandle hTokens = GCHandle.Alloc(batchTokens, GCHandleType.Pinned);
            GCHandle hPos = GCHandle.Alloc(batchPos, GCHandleType.Pinned);
            GCHandle hNSeq = GCHandle.Alloc(batchNSeq, GCHandleType.Pinned);
            GCHandle hLogits = GCHandle.Alloc(batchLogits, GCHandleType.Pinned);
            GCHandle hSeqIdPtrs = GCHandle.Alloc(seqIdPointers, GCHandleType.Pinned);

            var utf8Decoder = Encoding.UTF8.GetDecoder();
            byte[] byteBuffer = new byte[256];
            char[] charBuffer = new char[512];
            var accumulatedText = new StringBuilder();

            try
            {
                int lastEvalBatchSize = 0;
                for (int i = 0; i < nTokens; i += nBatchLimit)
                {
                    ct.ThrowIfCancellationRequested();

                    int evalBatchSize = Math.Min(nTokens - i, nBatchLimit);
                    lastEvalBatchSize = evalBatchSize;

                    for (int j = 0; j < evalBatchSize; j++)
                    {
                        batchTokens[j] = tokens[i + j];
                        batchPos[j] = i + j;
                        batchNSeq[j] = 1;
                        batchLogits[j] = (sbyte)((i + j == nTokens - 1) ? 1 : 0);
                    }

                    int result = _nativeApi.Decode(
                        ctxHandle,
                        evalBatchSize,
                        hTokens.AddrOfPinnedObject(),
                        hPos.AddrOfPinnedObject(),
                        hNSeq.AddrOfPinnedObject(),
                        hSeqIdPtrs.AddrOfPinnedObject(),
                        hLogits.AddrOfPinnedObject());

                    if (result != 0)
                    {
                        _logger.LogWarning("llama_decode returned error code during prompt eval: {Code}", result);
                        yield break;
                    }
                }

                currentPos = nTokens;

                while (generated < maxTokens)
                {
                    ct.ThrowIfCancellationRequested();
                    int logitIndex = 0;

                    if (generated == 0)
                    {
                        logitIndex = lastEvalBatchSize - 1;
                    }
                    else
                    {
                        batchTokens[0] = tokens[nTokens + generated - 1];
                        batchPos[0] = currentPos++;
                        batchNSeq[0] = 1;
                        batchLogits[0] = 1;

                        int result = _nativeApi.Decode(
                            ctxHandle,
                            1,
                            hTokens.AddrOfPinnedObject(),
                            hPos.AddrOfPinnedObject(),
                            hNSeq.AddrOfPinnedObject(),
                            hSeqIdPtrs.AddrOfPinnedObject(),
                            hLogits.AddrOfPinnedObject());

                        if (result != 0)
                        {
                            _logger.LogWarning("llama_decode returned error code during generation: {Code}", result);
                            yield break;
                        }
                    }

                    int token = _nativeApi.SamplerSample(sampler, ctxHandle, logitIndex);

                    if (token == eos || token < 0)
                        yield break;

                    _nativeApi.SamplerAccept(sampler, token);

                    tokens[nTokens + generated] = token;
                    generated++;

         
                    int pieceSize = _nativeApi.TokenToPiece(vocab, token, byteBuffer, byteBuffer.Length, 0, true);

                    if (pieceSize > byteBuffer.Length)
                    {
                        byteBuffer = new byte[pieceSize];
                        pieceSize = _nativeApi.TokenToPiece(vocab, token, byteBuffer, byteBuffer.Length, 0, true);
                    }

                    if (pieceSize > 0)
                    {
                        int charsDecoded = utf8Decoder.GetChars(byteBuffer, 0, pieceSize, charBuffer, 0, flush: false);

                        if (charsDecoded > 0)
                        {
                            string piece = new string(charBuffer, 0, charsDecoded);
                            accumulatedText.Append(piece);

                            string currentText = accumulatedText.ToString();

                            if (currentText.Contains("<|im_end|>") || currentText.Contains("<|endoftext|>"))
                            {
                                yield break;
                            }

                            if (request.Stop != null && request.Stop.Count > 0)
                            {
                                bool stopSequenceFound = false;
                                foreach (var stopSeq in request.Stop)
                                {
                                    if (!string.IsNullOrEmpty(stopSeq) && currentText.Contains(stopSeq))
                                    {
                                        stopSequenceFound = true;
                                        break;
                                    }
                                }

                                if (stopSequenceFound)
                                {
                                    yield break;
                                }
                            }

                            yield return piece;
                        }
                    }
                }

                int finalChars = utf8Decoder.GetChars(byteBuffer, 0, 0, charBuffer, 0, flush: true);
                if (finalChars > 0)
                {
                    string finalPiece = new string(charBuffer, 0, finalChars);
                    yield return finalPiece;
                }
            }
            finally
            {
                _nativeApi.SamplerFree(sampler);

                hTokens.Free();
                hPos.Free();
                hNSeq.Free();
                hLogits.Free();
                hSeqIdPtrs.Free();
                hSeqIdValue.Free();
            }
        }
    }
}