using InstantAIGate.Infrastructure.Inference.Native;
using Microsoft.Extensions.Logging;
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace InstantAIGate.Infrastructure.Inference
{
    /// <summary>
    /// Provides a memory-safe boundary for evaluating tokens and embeddings through the LLaMA engine.
    /// Manages pinned memory allocations for LlamaBatch structures and strictly handles native errors.
    /// </summary>
    public sealed class LlamaEngineFacade
    {
        private readonly ILogger<LlamaEngineFacade> _logger;

        public LlamaEngineFacade(ILogger<LlamaEngineFacade> logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Evaluates a batch of standard text tokens safely by pinning managed memory arrays.
        /// </summary>
        /// <param name="contextHandle">The active LLaMA inference context.</param>
        /// <param name="tokens">Array of text tokens to evaluate.</param>
        /// <param name="startPosition">The sequence position to start decoding from.</param>
        /// <returns>The number of tokens successfully evaluated.</returns>
        /// <exception cref="InvalidOperationException">Thrown if native decoding fails.</exception>
        public int DecodeTextBatchSafe(IntPtr contextHandle, int[] tokens, int startPosition)
        {
            if (contextHandle == IntPtr.Zero) throw new ArgumentException("Context handle cannot be zero.", nameof(contextHandle));
            if (tokens == null || tokens.Length == 0) return 0;

            int batchSize = tokens.Length;
            int[] pos = new int[batchSize];
            int[] nSeqId = new int[batchSize];
            sbyte[] logits = new sbyte[batchSize];

            for (int i = 0; i < batchSize; i++)
            {
                pos[i] = startPosition + i;
                nSeqId[i] = 1;
                logits[i] = (sbyte)((i == batchSize - 1) ? 1 : 0);
            }

            int seqIdValue = 0;
            GCHandle hSeqIdValue = GCHandle.Alloc(seqIdValue, GCHandleType.Pinned);
            IntPtr ptrSeqIdValue = hSeqIdValue.AddrOfPinnedObject();

            IntPtr[] seqIdPtrs = new IntPtr[batchSize];
            for (int i = 0; i < batchSize; i++)
            {
                seqIdPtrs[i] = ptrSeqIdValue;
            }

            GCHandle hTokens = GCHandle.Alloc(tokens, GCHandleType.Pinned);
            GCHandle hPos = GCHandle.Alloc(pos, GCHandleType.Pinned);
            GCHandle hNSeqId = GCHandle.Alloc(nSeqId, GCHandleType.Pinned);
            GCHandle hLogits = GCHandle.Alloc(logits, GCHandleType.Pinned);
            GCHandle hSeqIds = GCHandle.Alloc(seqIdPtrs, GCHandleType.Pinned);

            try
            {
                var batch = new NativeLlamaMethods.LlamaBatch
                {
                    NTokens = batchSize,
                    Token = hTokens.AddrOfPinnedObject(),
                    Embd = IntPtr.Zero,
                    Pos = hPos.AddrOfPinnedObject(),
                    NSeqId = hNSeqId.AddrOfPinnedObject(),
                    SeqId = hSeqIds.AddrOfPinnedObject(),
                    Logits = hLogits.AddrOfPinnedObject()
                };

                int result = NativeLlamaMethods.LlamaDecode(contextHandle, batch);
                if (result != 0)
                {
                    _logger.LogError("LlamaDecode failed for text batch with code: {Code}. Tokens count: {Count}", result, batchSize);
                    throw new InvalidOperationException($"Native text decoding failed with code {result}.");
                }

                return batchSize;
            }
            finally
            {
                hTokens.Free();
                hPos.Free();
                hNSeqId.Free();
                hLogits.Free();
                hSeqIds.Free();
                hSeqIdValue.Free();
            }
        }

        /// <summary>
        /// Evaluates a batch of visual embeddings generated by the Vision Engine.
        /// Bypasses the text token array and feeds raw vectors directly into the computational graph.
        /// </summary>
        /// <param name="contextHandle">The active LLaMA inference context.</param>
        /// <param name="visionData">The extracted embeddings and positional data from libmtmd.</param>
        /// <param name="startPosition">The sequence position to start decoding from.</param>
        /// <returns>The number of embeddings successfully evaluated.</returns>
        /// <exception cref="InvalidOperationException">Thrown if native decoding fails.</exception>
        public int DecodeVisionBatchSafe(IntPtr contextHandle, ExtractedVisionData visionData, int startPosition)
        {
            if (contextHandle == IntPtr.Zero) throw new ArgumentException("Context handle cannot be zero.", nameof(contextHandle));
            if (visionData == null || visionData.EmbeddingsPtr == IntPtr.Zero) throw new ArgumentException("Invalid vision data.", nameof(visionData));

            int batchSize = visionData.TokenCount;
            if (batchSize <= 0) return 0;

            int[] pos = new int[batchSize];
            int[] nSeqId = new int[batchSize];
            sbyte[] logits = new sbyte[batchSize];

            for (int i = 0; i < batchSize; i++)
            {
                // Aligning M-RoPE temporal sequence to the linear textual sequence
                pos[i] = startPosition + i;
                nSeqId[i] = 1;
                logits[i] = (sbyte)((i == batchSize - 1) ? 1 : 0);
            }

            int seqIdValue = 0;
            GCHandle hSeqIdValue = GCHandle.Alloc(seqIdValue, GCHandleType.Pinned);
            IntPtr ptrSeqIdValue = hSeqIdValue.AddrOfPinnedObject();

            IntPtr[] seqIdPtrs = new IntPtr[batchSize];
            for (int i = 0; i < batchSize; i++)
            {
                seqIdPtrs[i] = ptrSeqIdValue;
            }

            GCHandle hPos = GCHandle.Alloc(pos, GCHandleType.Pinned);
            GCHandle hNSeqId = GCHandle.Alloc(nSeqId, GCHandleType.Pinned);
            GCHandle hLogits = GCHandle.Alloc(logits, GCHandleType.Pinned);
            GCHandle hSeqIds = GCHandle.Alloc(seqIdPtrs, GCHandleType.Pinned);

            try
            {
                var batch = new NativeLlamaMethods.LlamaBatch
                {
                    NTokens = batchSize,
                    Token = IntPtr.Zero, // Must be zero when using embeddings
                    Embd = visionData.EmbeddingsPtr,
                    Pos = hPos.AddrOfPinnedObject(),
                    NSeqId = hNSeqId.AddrOfPinnedObject(),
                    SeqId = hSeqIds.AddrOfPinnedObject(),
                    Logits = hLogits.AddrOfPinnedObject()
                };

                int result = NativeLlamaMethods.LlamaDecode(contextHandle, batch);
                if (result != 0)
                {
                    _logger.LogError("LlamaDecode failed for vision embeddings with code: {Code}. Embeddings count: {Count}", result, batchSize);
                    throw new InvalidOperationException($"Native vision decoding failed with code {result}.");
                }

                return batchSize;
            }
            finally
            {
                hPos.Free();
                hNSeqId.Free();
                hLogits.Free();
                hSeqIds.Free();
                hSeqIdValue.Free();
            }
        }

        /// <summary>
        /// Samples the next most probable token from the model's output logits.
        /// </summary>
        public int SampleTokenSafe(IntPtr samplerChain, IntPtr contextHandle, int logitIndex)
        {
            if (samplerChain == IntPtr.Zero) throw new ArgumentException("Sampler chain cannot be zero.", nameof(samplerChain));
            return NativeLlamaMethods.LlamaSamplerSample(samplerChain, contextHandle, logitIndex);
        }

        /// <summary>
        /// Accepts the sampled token to update internal sampler states (e.g., repetition penalties).
        /// </summary>
        public void AcceptTokenSafe(IntPtr samplerChain, int token)
        {
            if (samplerChain != IntPtr.Zero)
            {
                NativeLlamaMethods.LlamaSamplerAccept(samplerChain, token);
            }
        }

        private readonly Decoder _utf8Decoder = Encoding.UTF8.GetDecoder();
        private readonly byte[] _byteBuffer = new byte[256];
        private readonly char[] _charBuffer = new char[512];

        /// <summary>
        /// Safely converts a token into text using a persistent UTF-8 decoder to handle multi-byte characters.
        /// </summary>
        public string TokenToTextSafe(IntPtr vocab, int token)
        {
            if (vocab == IntPtr.Zero) return string.Empty;

            int size = NativeLlamaMethods.LlamaTokenToPiece(vocab, token, _byteBuffer, _byteBuffer.Length, 0, true);

            if (size > _byteBuffer.Length)
            {
                // Dynamic resize if token piece is exceptionally large
                byte[] largerBuffer = new byte[size];
                size = NativeLlamaMethods.LlamaTokenToPiece(vocab, token, largerBuffer, largerBuffer.Length, 0, true);

                int chars = _utf8Decoder.GetChars(largerBuffer, 0, size, _charBuffer, 0, flush: false);
                return chars > 0 ? new string(_charBuffer, 0, chars) : string.Empty;
            }

            if (size <= 0) return string.Empty;

            int charsDecoded = _utf8Decoder.GetChars(_byteBuffer, 0, size, _charBuffer, 0, flush: false);
            return charsDecoded > 0 ? new string(_charBuffer, 0, charsDecoded) : string.Empty;
        }
    }
}